link/client/urls.py
from django.urls import path

from .views import ClientListView


urlpatterns = [
    path('list-clients', ClientListView.as_view(), name='clientList'),
    
]

link/core/urls.py
from django.urls import path
from core.views import HomePageView 


urlpatterns = [
    path('', HomePageView.as_view(), name='home'),
]

link/link/urls.py
from django.contrib import admin
from django.conf.urls import url
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('preform/', include('preform.urls')),
    path('client/', include('client.urls')),
    path('', include('core.urls')),
]

link/preform/urls.py
from django.urls import path
from preform.views import PreformCreateView, PreformListView


urlpatterns = [
    path('preform', PreformCreateView.as_view(), name='preformCreate'),
    path('list-preforms', PreformListView.as_view(), name='preformList'),
]

link/client/models.py
from django.db import models
from django.forms import model_to_dict # Convierte una clase a Diccionario


# Create your models here.

class Company(models.Model):
    """Model definition for Company."""

    # TODO: Define fields here
    logo = models.ImageField()
    name = models.CharField(max_length=100)
    phone = models.PositiveIntegerField()
    mail = models.EmailField()

    class Meta:
        """Meta definition for Company."""

        verbose_name = 'Company'
        verbose_name_plural = 'Companys'

    def __str__(self):
        """Unicode representation of Company."""
        return '%s' % (self.name)


class Branch(models.Model):
    """Model definition for Branch."""

    # TODO: Define fields here
    identifier = models.PositiveSmallIntegerField()
    name = models.CharField(max_length=100)
    address = models.CharField(max_length=100, blank=True, null=True)
    company = models.ForeignKey(Company, on_delete=models.CASCADE, blank=True, null=True)

    class Meta:
        """Meta definition for Branch."""

        verbose_name = 'Branch'
        verbose_name_plural = 'Branchs'

    def toJSON(self):
        item = model_to_dict(self)
        item['identifier'] = self.identifier
        item['name'] = self.name
        item['address'] = self.address
        item['company'] = self.company.name
        return item

    def __str__(self):
        """Unicode representation of Branch."""
        return '%s - %s' % (self.name, self.company)
        

link/core/models.py
from django.db import models

# Create your models here.


class Detail(models.Model):
    """Model definition for Detail."""

    # TODO: Define fields here
    description = models.TextField()
    cost = models.DecimalField(max_digits=6, decimal_places=2)

    class Meta:
        """Meta definition for Detail."""

        verbose_name = 'Detail'
        verbose_name_plural = 'Details'

    def __str__(self):
        """Unicode representation of Detail."""
        pass

link/invoice/models.py
from django.db import models

# Create your models here.

link/preform/models.py
from django.db import models
from core.models import Detail
from client.models import Branch
import datetime

# Import Singnals
from django.db.models.signals import post_save
from django.dispatch import receiver

# Create your models here.

class Preform(models.Model):
    """Model definition for Preform."""

    STATUS_CHOICES = [
    (0, 'executed'),
    (1, 'Validated'),
    (2, 'Canceled'),
]

    # TODO: Define fields here
    identifier = models.PositiveSmallIntegerField(editable=False, null=True, blank=True)
    date = models.DateField(auto_now_add=True)
    client = models.ForeignKey(Branch, on_delete=models.CASCADE)
    total_cost = models.DecimalField(
        max_digits=8, decimal_places=2, editable=False,
        null=True, blank=True)
    status = models.PositiveSmallIntegerField(choices=STATUS_CHOICES, default=0)

    class Meta:
        """Meta definition for Preform."""

        verbose_name = 'Preform'
        verbose_name_plural = 'Preforms'

    def generateIdentifier(self):
        identifier = 'PREFL-'
        identifier += str(self.client.company.name[:1]) + str(self.id)
        return identifier

    def generateTotalCost(self):
        cost = 0.00
        details = DetailPreform.objects.filter(preform = self.id)
        if details == None:
            cost = 0.00
        else:
            for item in details:
                cost += item.cost
        self.total_cost = cost
        return cost


    def __str__(self):
        """Unicode representation of Preform."""
        return '%s, %s, %s' % (self.date, 'Lugar', self.total_cost)

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)
        self.generateTotalCost()



class DetailPreform(Detail):
    """Model definition for DetailPreform."""

    # TODO: Define fields here
    preform = models.ForeignKey(Preform, on_delete=models.CASCADE)

    class Meta:
        """Meta definition for DetailPreform."""

        verbose_name = 'DetailPreform'
        verbose_name_plural = 'DetailPreforms'

    def __str__(self):
        """Unicode representation of DetailPreform."""
        pass

link/client/views.py
from django.shortcuts import render
from django.views.generic.list import ListView

from client.models import Branch

# Create your views here.


class ClientListView(ListView):
    model = Branch

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['link'] = 'client'
        return context

link/core/views.py
from django.shortcuts import render
from django.views.generic.base import TemplateView

# Create your views here.

class HomePageView(TemplateView):

    template_name = 'core/home.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['link'] = 'client'
        return context

link/invoice/views.py
from django.shortcuts import render

# Create your views here.

link/preform/views.py
from django.shortcuts import render
from django.urls import reverse, reverse_lazy
from django.http import JsonResponse
from django.utils import timezone
# Importamos las platillas a utilizar 
from django.views.generic.edit import CreateView
from django.views.generic.list import ListView
from django.views.generic import TemplateView 
# Importamos los decoradores
from django.utils.decorators import method_decorator
from django.views.decorators.csrf import csrf_exempt
from django.contrib.auth.decorators import login_required
# Importamos los modelos
from preform.models import Branch, Preform

# Create your views here.

class PreformCreateView(CreateView):
    model = Preform
    fields = '__all__'
    success_url = reverse_lazy('customersList')

    @method_decorator(csrf_exempt)
    @method_decorator(login_required)
    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(request, *args, **kwargs)
    
    # Sobreescribimos el metodo POST
    def post(self, request, *args, **kwargs):
        # Se crea un diccionario donde se enviara la data
        data = {}
        try:
            action = request.POST['action']
            if action == 'searchdata':
                data = []
                for c in Branch.objects.filter(name__icontains=request.POST['term'])[0:10]:
                    item = c.toJSON()
                    item['text'] = (c.name + ' - ' + c.company.name)
                    data.append(item)
            else:
                data['error'] = 'Ha ocurrido un error'
        except Exception as e:
            data['error'] = str(e)
        return JsonResponse(data, safe=False)
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['now'] = timezone.now()
        context['action'] = 'add'
        context["titulo"] = 'Preformas' 
        return context

class PreformListView(ListView):
    model = Preform

link/client/templates/client/branch_list.html
<!-- Extendemos el template list_base -->
{% extends "core/list_base.html" %}

<!-- Modificamos el contenido -->
<!-- Titulo -->
{% block page_title %}Clientes {% endblock page_title %}
<!-- Subtitulo -->
{% block page_subtitle %}Listado de Clientes Registrados {% endblock page_subtitle %}
<!-- Tabla de la lista -->
{% block table_list %}
<table id="clients-table" class="table display responsive nowrap">
    <thead>
        <tr>
            <th><i class="fas fa-store-alt"></i>Sucursal</th>
            <th><i class="fas fa-calendar-day"></i>Compania</th>
            <th><i class="fas fa-calendar-day"></i>Telefono</th>
            <th><i class="fas fa-calendar-day"></i>Email</th>
            <th><i class="fas fa-sack-dollar"></i>Direccion</th>
            <th><i class="fas fa-sack-dollar"></i>Acciones</th>
        </tr>
    </thead>
    <tbody>
        {% for client in object_list %}
        <tr>
            <td>{{client.id}}-{{client.name}}</td>
            <td>{{client.company}}</td>
            <td>{{client.company.email}}</td>
            <td>{{client.company.phone}}</td>
            <td>{{client.address}}</td>
            <td>
                <div class="actions">
                    <button><i class="fas fa-edit"></i></button>
                    <button><i class="fas fa-trash"></i></button>
                </div>
            </td>
        </tr>
        {% empty %}
        <tr>
            <td rowspan="3">No clients yet.</td>
        </tr>
        {% endfor %}
    </tbody>
</table>
{% endblock table_list %}

link/core/templates/core/base.html
{% load static %}
<!DOCTYPE html>
<html lang="es">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="shortcut icon" href="{% static 'assets/img/kp_black.ico' %}">
    <title>{% block title %}{% endblock title %}</title>

    <!-- Fonts -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Dosis:wght@200;300;500;800&display=swap" rel="stylesheet">

    <!-- Styles CSS -->
    <link rel="stylesheet" href='{% static "css/base.css" %}'>
    <link rel="stylesheet" href='{% static "css/base1280.css" %}' media="(min-width: 1280px)">

    <!-- Font Awesome -->
    <link href="https://kit-pro.fontawesome.com/releases/v5.15.3/css/pro.min.css" rel="stylesheet">

    <!-- DataTables -->

    {% block styles_load %}{% endblock styles_load %}


</head>

<body>
    <!-- Menu -->
    <div class="menu">
        <div class="nav">
            <nav class="navbar">
                <div class="logo">
                    <picture>
                        <img src="{% static 'assets/img/LINK.ico' %}" alt="">
                    </picture>
                </div>
                <div class="info">
                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quo, earum?</p>
                </div>
                <div class="hamburger-menu">
                    <div class="bar bar1"></div>
                    <div class="bar bar2"></div>
                    <div class="bar bar3"></div>
                </div>
            </nav>
        </div>
        <div class="menu-item">
            {% include "core/menu.html" %}
        </div>
    </div>

    <hr>

    <!-- Content -->
    <div class="main">
        {% block content %} {% endblock content %}
    </div>
    </div>

    <!-- Footer -->
    <footer class="footer">
        <div class="info">
            <span>By <picture class="picture">
                <source media="(max-width: 1024px)" srcset="{% static 'assets/img/kp_black.ico' %}">
                <img src="{% static 'assets/img/kp_white.ico' %}" alt="KP">
            </picture> KodePrint 2021 &copy;</span>
        </div>
    </footer>

    <!-- JQuery -->
    <script src="{% static 'js/jquery-3.6.0.min.js' %}"></script>
    <!-- DataTable -->

    {% block scripts_load %}{% endblock scripts_load %}


    <!-- Scripts -->
    <script src='{% static "js/link.js" %}'></script>
    <script src='{% static "js/functions.js" %}'></script>

    {% block scritps %} {% endblock scritps %}
    <!-- selected-link -->
    <script>
        var path = '{{request.path}}';
        let home = document.querySelector('.home');
        let preform = document.querySelector('.preform');
        let invoice = document.querySelector('.invoice');
        let client = document.querySelector('.client');

        validatePath()

        function selected_link(link) {
            home.classList.remove('selected');
            preform.classList.remove('selected');
            invoice.classList.remove('selected');
            client.classList.remove('selected');

            link.classList.add('selected');
        }

        function validatePath() {
            if (path.indexOf('home') === 1) {
                selected_link(home);
            } else if (path.indexOf('preform') === 1) {
                selected_link(preform);
            } else if (path.indexOf('client') === 1) {
                selected_link(client);
            } else {
                selected_link(invoice);
            }
        }
        /*
                let home = document.querySelector('.home');
                let preform = document.querySelector('.preform');
                let invoice = document.querySelector('.invoice');
                let client = document.querySelector('.client');
                let path = '{{request.path}}';

                console.log('{{request.path}}')

                function selected_link(link) {
                    home.classList.remove('selected');
                    preform.classList.remove('selected');
                    invoice.classList.remove('selected');
                    client.classList.remove('selected');

                    link.classList.add('selected');
                }

                editPath()

                function editPath() {
                    let link = path.split('/');
                    link.findIndex(preform)
                };
                if (path == '') {
                    selected_link(home);
                } else if (path == 'preform') {
                    selected_link(preform);
                } else if (path == 'client') {
                    selected_link(client);
                }*/
    </script>
</body>

</html>

link/core/templates/core/form_base.html
{% extends "core/base.html" %} {% load static %}

<!-- Incluimos el contenido -->
{% block content %}
<div class="content">
    <div class="page_content_title">
        <h2 class="page_title">{% block page_title %}Dashboard{% endblock page_title %}</h2>
        <div class="page_subtitle">
            <span>
        {% block page_subtitle %}Pagina de Inicio..!{% endblock page_subtitle %}
            </span>
        </div>
        <div class="page_content">
            {% block page_content %} {% endblock page_content %}
        </div>
    </div>
</div>
{% endblock content %}
<!-- Carga de SCRITPS adiccionales -->
{% block scripts_load %}
<script src="{% static 'plugins/Select2/js/select2.min.js' %}"></script>
<script src="{% static 'plugins/Select2/js/i18n/es.js' %}"></script>
<script src="{% static 'js/preforms.js' %}"></script>
{% endblock scripts_load %}

link/core/templates/core/list_base.html
{% extends "core/base.html" %}

<!-- Incluimos el contenido -->
{% block content %}
<div class="content">
    <div class="page_content_title">
        <h2 class="page_title">{% block page_title %}Dashboard{% endblock page_title %}</h2>
        <div class="page_subtitle">
            <span>
        {% block page_subtitle %}Pagina de Inicio..!{% endblock page_subtitle %}
            </span>
            <a href="{% url 'preformCreate' %}" class="add"><i class="far fa-layer-plus"></i></a>
        </div>
        <div class="page_content">

            {% block table_list %} {% endblock table_list %}

        </div>
    </div>
</div>
{% endblock content %}

<!-- Scripts -->
{% block scritps %}
<script>
    $(document).ready(function() {
        //adminDataTable()
    });

    /*function adminDataTable() {
        $('.table').DataTable({
            responsive: true,
            columnDefs: [
                { responsivePriority: 0, targets: 0 },
                { responsivePriority: 1, targets: -1 }
            ],
            "language": {
                "emptyTable": "<i>No hay datos disponibles</i>",
                "info": "Del _START_ al _END_ de _TOTAL_",
                "infoEmpty": "Mostrando 0 registros de un total de 0",
                "infoFiltered": "(<i><small>filtrados de un total de _MAX_ registros</small></i>)",
                "infoPostFix": "(actualizados)",
                "lengthMenu": "Mostrar _MENU_ registros",
                "loadingRecords": "Cargando...",
                "processing": "Procesando...",
                "search": "<b><i class='table-icon fas fa-search'></i> Buscar</b>",
                "searchPlaceholder": "",
                "zeroRecords": "<i class='table-icon fad fa-sad-tear'></i> No se han econtrado conicidencias.",
                "paginate": {
                    "first": "Primera",
                    "last": "Última",
                    "next": "<i class='table-icon fad fa-chevron-right'></i>",
                    "previous": "<i class='table-icon fad fa-chevron-left'></i>",
                },
                "aria": {
                    "sortAscending": "Ordenación ascendente",
                    "sortDescending": "Ordenación decendente",
                },

            },
            "lengthMenu": [
                [3, 5, 10, 20, 50, 100, -1],
                [3, 5, 10, 20, 50, 100, "Todos"]
            ],
            "iDisplayLength": 8,
        })
    }*/
</script>
{% endblock scritps %}

link/core/templates/core/menu.html
<div class="list-menu">
    <div class="fondo"></div>
    <ul class="list">
        <li class="item">
            <a class="item-link home" href="{% url 'home' %}"><i class="fas fa-home-lg-alt"></i><span>Home</span></a>
        </li>
        <li class="item">
            <a class="item-link preform" href="{% url 'preformList' %}"><i class="fas fa-file-invoice"></i><span>Preformas</span></a>
        </li>
        <li class="item">
            <a class="item-link invoice" href=""><i class="fas fa-file-invoice-dollar"></i><span>Facturas</span></a>
        </li>
        <li class="item">
            <a class="item-link client" href="{% url 'clientList' %}"><i class="fas fa-store-alt"></i><span>Clientes</span></a>
        </li>
    </ul>
    <div class="btn-menu">
        <button class="collapse-button"><i class="far fa-arrow-alt-from-right"></i></button>
    </div>
</div>

link/preform/templates/preform/preform_form.html
{% extends 'core/form_base.html' %} {% load static %}

<!-- Cargamos los estilos que se necesiten -->
{% block styles_load %}
<link href="{% static 'plugins/Select2/css/select2.min.css' %}" rel="stylesheet"> {% endblock styles_load %}

<!-- Modificamos el contenido -->
<!-- Titulo -->
{% block page_title %}<i class="fas fa-file-invoice"></i> Nueva Preforma{% endblock page_title %}
<!-- Subtitulo -->
{% block page_subtitle %}<i class="fas fa-plus"></i> Agregando una nueva preforma {% endblock page_subtitle %} {% block page_content %}
<form class="form_add" action="">
    <div class="client_data">
        <div class="title_client_data">
            <h4>Datos del Cliente</h4>
            <span class="date">{{now|date}}</span>
        </div>
        <div class="body_client_data">
            </select>
            <select class="preforms_select" name="client" id="id_client" style="width: 100%;" required></select>
        </div>
    </div>
    <div class="detail_data">
        <div class="title_detail_data">
            <h4>Detalles de la Preforma</h4>
        </div>
        <!-- Table Content -->
        <div class="body_detail_data">
            <div class="detail_input_data">
                <div class="input_group">
                    <input name="description" type="text" placeholder="Descripción" autocomplete="off">
                    <input name="mount" type="number" placeholder="Monto">
                    <button class="add_detail_btn"><i class="fas fa-plus"></i></button>
                </div>
            </div>
            <table class="table_detail">
                <thead>
                    <tr>
                    </tr>
                </thead>
                <tbody></tbody>
                <tfoot>

                </tfoot>
            </table>
        </div>
    </div>
    <!-- Buttons Content -->
</form>
<div class="buttons_form">
    <button onclick="backPage()" class="btn_form">Regresar</button>
    <button class="btn_form">Registrar</button>
</div>
{% endblock page_content %}

link/preform/templates/preform/preform_list.html
<!-- Extendemos el template list_base -->
{% extends "core/list_base.html" %}

<!-- Modificamos el contenido -->
<!-- Titulo -->
{% block page_title %}<i class="fas fa-file-invoice"></i> Preformas{% endblock page_title %}
<!-- Subtitulo -->
{% block page_subtitle %}Listado de Preformas Ingresadas {% endblock page_subtitle %}
<!-- Tabla de la lista -->
{% block table_list %}
<table id="clients-table" class="display responsive nowrap table">
    <thead>
        <tr>
            <th><i class="fas fa-store-alt"></i>Identificador</th>
            <th><i class="fas fa-calendar-day"></i>Fecha</th>
            <th><i class="fas fa-calendar-day"></i>Sucursal</th>
            <th><i class="fas fa-calendar-day"></i>Compania</th>
            <th><i class="fas fa-calendar-day"></i>Monto</th>
            <th><i class="fas fa-sack-dollar"></i>Estado</th>
            <th><i class="fas fa-sack-dollar"></i>Acciones</th>
        </tr>
    </thead>
    <tbody>
        {% for preform in object_list %}
        <tr>
            <td>{{preform.generateIdentifier}}</td>
            <td>{{preform.date}}</td>
            <td>{{preform.client}}</td>
            <td>{{preform.client.company}}</td>
            <td>{{preform.generateTotalCost}}</td>
            <td>{{preform.status}}</td>
            <td>
                <div class="actions">
                    <button><i class="fas fa-edit"></i></button>
                    <button><i class="fas fa-trash"></i></button>
                </div>
            </td>
        </tr>
        {% empty %}
        <tr>
            <td rowspan="3">No clients yet.</td>
        </tr>
        {% endfor %}
    </tbody>
</table>
{% endblock table_list %}